<a href="https://colab.research.google.com/github/tusharbansal22/Tensorflow-Notebooks/blob/main/RNN_Shapes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print(tf.__version__)

2.9.2


In [2]:
from tensorflow.keras.layers import Input, SimpleRNN,Dense,Flatten
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import SGD,Adam

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [3]:
N=1
T=10
D=3
K=2
X=np.random.randn(N,T,D)

In [4]:
M=5
i=Input(shape=(T,D))
x=SimpleRNN(M)(i)
x=Dense(K)(x)

model=Model(i,x)

In [5]:
Yhat=model.predict(X)
print(Yhat)

1/1 [==============================] - 0s 267ms/step
[[0.4674355 0.7247561]]


In [6]:
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 10, 3)]           0         
                                                                 
 simple_rnn (SimpleRNN)      (None, 5)                 45        
                                                                 
 dense (Dense)               (None, 2)                 12        
                                                                 
Total params: 57
Trainable params: 57
Non-trainable params: 0
_________________________________________________________________


In [7]:
model.layers[1].get_weights()

[array([[ 0.47998756,  0.05541354,  0.32921344, -0.18436188, -0.2187177 ],
        [ 0.71800095,  0.63410145, -0.70122266,  0.8535499 , -0.5118731 ],
        [-0.7637111 , -0.62376356, -0.7674349 ,  0.02510691,  0.30702072]],
       dtype=float32),
 array([[ 0.58341134, -0.6377015 ,  0.18079713,  0.23032227,  0.40894014],
        [ 0.0474452 , -0.23861119,  0.33476776,  0.4044501 , -0.815576  ],
        [-0.5855957 , -0.539912  , -0.52304155,  0.297922  ,  0.05694431],
        [-0.5113557 , -0.30633524,  0.6918738 , -0.37571725,  0.15754756],
        [-0.23015901,  0.3886581 ,  0.32090643,  0.7439429 ,  0.3735503 ]],
       dtype=float32),
 array([0., 0., 0., 0., 0.], dtype=float32)]

In [9]:
a,b,c=model.layers[1].get_weights()
print(a.shape,b.shape,c.shape)

(3, 5) (5, 5) (5,)


In [10]:
Wx,Wh,bh=model.layers[1].get_weights()
Wo,bo=model.layers[2].get_weights()

In [11]:
h_last=np.zeros(M)
x=X[0]
Yhats=[]

for t in range(T):
  h=np.tanh(x[t].dot(Wx)+h_last.dot(Wh)+bh)
  y=h.dot(Wo)+bo
  Yhats.append(y)

  h_last=h

print(Yhats[-1])

[0.46743558 0.7247562 ]
