<a href="https://colab.research.google.com/github/tusharbansal22/Tensorflow-Notebooks/blob/main/numpy/Numpy_Tut.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Array vs Lists

In [1]:
import numpy as np

In [2]:
L=[1,2,3]

In [3]:
A=np.array([1,2,3])

In [4]:
for e in L:
  print(e)

1
2
3


In [6]:
for e in A:
  print(e)

1
2
3


In [7]:
L.append(4 )

In [8]:
A.append(4)

AttributeError: ignored

In [9]:
L+[5]

[1, 2, 3, 4, 5]

In [10]:
A+np.array([4])

array([5, 6, 7])

In [11]:
A+np.array([4,5,6])

array([5, 7, 9])

In [12]:
A+np.array([4,5])

ValueError: ignored

In [13]:
2*A

array([2, 4, 6])

In [14]:
2*L

[1, 2, 3, 4, 1, 2, 3, 4]

In [15]:
L2=[]
for e in L:
  L2.append(e+3)

In [16]:
L2

[4, 5, 6, 7]

In [17]:
L2=[e+3 for e in L]

In [18]:
L2=[]
for e in L:
  L2.append(e**2)
L2

[1, 4, 9, 16]

In [19]:
A**2

array([1, 4, 9])

In [20]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [21]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [22]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [23]:
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])

## Dot Product

In [25]:
a=np.array([1,2])
b=np.array([3,4])

In [26]:
dot=0
for e,f in zip(a,b):
  dot+=e*f
dot

11

In [28]:
dot=0
for i in range(len(a)):
  dot+= a[i]*b[i]

dot 

11

In [30]:
a*b

array([3, 8])

In [29]:
np.sum(a*b)

11

In [31]:
(a*b).sum()

11

In [32]:
np.dot(a,b )

11

In [33]:
a.dot(b)

11

In [34]:
a @ b

11

In [37]:
amag= np.sqrt((a**2).sum())

In [38]:
np.linalg.norm(a)

2.23606797749979

In [39]:
cosangle = a.dot(b)/ (np.linalg.norm(a)* np.linalg.norm(b))
cosangle

0.9838699100999074

In [40]:
angle = np.arccos(cosangle)
angle

0.17985349979247847

## Matrices

In [41]:
L=[[1,2],[3,4]]

In [42]:
L[0]

[1, 2]

In [43]:
L[0][1]

2

In [44]:
A=np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [45]:
A[0][1]

2

In [46]:
A[0,1]

2

In [47]:
A[:,0]

array([1, 3])

In [48]:
A.T

array([[1, 3],
       [2, 4]])

In [49]:
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [50]:
np.exp(L)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [52]:
B=np.array([[1,2,3],[4,5,6]])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
A.dot(B)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [54]:
A.dot(B.T)

ValueError: ignored

In [55]:
np.linalg.det(A)

-2.0000000000000004

In [56]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [57]:
np.linalg.inv(A).dot(A)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [58]:
np.trace(A)

5

In [59]:
np.diag(A)

array([1, 4])

In [61]:
np.diag([1,4])

array([[1, 0],
       [0, 4]])

In [63]:
np.linalg.eig(A)

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [64]:
Lam, V=np.linalg.eig(A)

In [65]:
V[:,0]*Lam[0] == A@V[:,0]

array([ True, False])

In [66]:
V[:,0]*Lam[0] ,A@V[:,0]

(array([ 0.30697009, -0.21062466]), array([ 0.30697009, -0.21062466]))

In [67]:
np.allclose(V[:,0]*Lam[0] ,A@V[:,0])

True

In [68]:
 np.allclose( V @ np.diag(Lam), A@V)

True