<a href="https://colab.research.google.com/github/tusharbansal22/Tensorflow-Notebooks/blob/main/numpy/Numpy_Tut_Live.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Solving Linear Systems


In [2]:
import numpy as np

In [3]:
A = np.array([[1,1],[1.5,4]])
b= np.array([2200,5050])

In [4]:
np.linalg.solve(A,b)

array([1500.,  700.])

In [5]:
np.linalg.inv(A).dot(b)

array([1500.,  700.])

## Generating Data

In [6]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
10*np.ones((2,3))

array([[10., 10., 10.],
       [10., 10., 10.]])

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.random.random()

0.3218061482155885

In [13]:
np.random.random((2,3))

array([[0.36932418, 0.9613564 , 0.49603577],
       [0.01497482, 0.55157234, 0.37287465]])

In [14]:
np.random.randn(2,3)

array([[ 0.43032157, -2.0248432 ,  0.3269421 ],
       [-0.15860522, -0.74677299, -0.74682824]])

In [15]:
R= np.random.randn(10000)

In [16]:
R.mean()

0.0005350487166137328

In [17]:
np.mean(R)

0.0005350487166137328

In [20]:
R.var()

1.0071113787697417

In [19]:
R.std()

1.003549390299123

In [21]:
R=np.random.randn(10000,3)

In [22]:
R.mean(axis=0)

array([-0.01157712,  0.02116549, -0.02200896])

In [23]:
R.mean(axis=1)

array([-1.11367664, -0.13080703,  0.441127  , ..., -0.36646279,
        0.53894188,  0.54314371])

In [24]:
R.mean(axis=1).shape

(10000,)

In [25]:
np.cov(R)

array([[ 1.53593762, -0.57086487, -0.02960145, ..., -0.99900291,
         1.53472809,  1.345474  ],
       [-0.57086487,  1.81160206, -1.25082139, ...,  0.68944358,
        -0.69442135, -1.07629779],
       [-0.02960145, -1.25082139,  0.99605059, ..., -0.23173604,
         0.06825292,  0.42866412],
       ...,
       [-0.99900291,  0.68944358, -0.23173604, ...,  0.7130521 ,
        -1.02288225, -0.9897383 ],
       [ 1.53472809, -0.69442135,  0.06825292, ..., -1.02288225,
         1.5431339 ,  1.38908988],
       [ 1.345474  , -1.07629779,  0.42866412, ..., -0.9897383 ,
         1.38908988,  1.38622356]])

In [27]:
np.cov(R).shape

(10000, 10000)

In [28]:
np.cov(R.T)

array([[ 1.00543781, -0.00607876, -0.00547904],
       [-0.00607876,  0.98227854,  0.00967274],
       [-0.00547904,  0.00967274,  0.99361498]])

In [29]:
np.cov(R,rowvar=False)

array([[ 1.00543781, -0.00607876, -0.00547904],
       [-0.00607876,  0.98227854,  0.00967274],
       [-0.00547904,  0.00967274,  0.99361498]])

In [30]:
np.random.randint(0,10,size=(3,3))

array([[0, 0, 5],
       [1, 9, 7],
       [0, 5, 4]])

In [31]:
np.random.choice(10,size=(3,3))

array([[3, 7, 7],
       [0, 9, 2],
       [4, 8, 1]])